### ISSUE TITLE
RuntimeError: Best model can not loaded!

### ISSUE THREAD

**Issue by Ashesh3** [johnnyvf24/kalah-alpha-zero#1]
Hello!

i saw that there are no pretrained models in the data directory, so i am trying to train one from scratch.

I used: `python src/kalah_zero/run.py opt`

But it seems to be trying to load existing model which isn't there.
```
2019-07-09 00:55:22,564@kalah_zero.manager INFO # config type: normal
Using TensorFlow backend.
2019-07-09 00:55:28.058383: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "src/kalah_zero/run.py", line 17, in <module>
    manager.start()
  File "src\kalah_zero\manager.py", line 45, in start
    return optimize.start(config)
  File "src\kalah_zero\worker\optimize.py", line 25, in start
    return OptimizeWorker(config).start()
  File "src\kalah_zero\worker\optimize.py", line 38, in start
    self.model = self.load_model()
  File "src\kalah_zero\worker\optimize.py", line 131, in load_model
    raise RuntimeError(f"Best model can not loaded!")
RuntimeError: Best model can not loaded!
```

How can i train the model?

**Comment by Ashesh3** [comment]
Solution: run `python src/kalah_zero/run.py self` and let it generate a random train model (it'll take some time, check logs)

issue solved.
